server:
  port: 8080

spring:
  application:
    name: operations-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/operations
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

springdoc:
  api-docs:
    path: /docs

eureka:
  client:
    enabled: false